[package]
name = "checksum"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.3.9"
sha2 = "0.10.6"
md-5 = "0.10.5"
sha1 = "0.10.5"
digest = "0.10.6"
tiger = "0.2.1"
ripemd = "0.1.3"
hex = "0.4.3"
colored = "2.2.0"
